// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuPVRb2slEHddOtix-z7-gj382RiNQ_CE',
    appId: '1:345387617265:web:ebfaa28d5e8f7402db1250',
    messagingSenderId: '345387617265',
    projectId: 'restaurantapp-ed895',
    authDomain: 'restaurantapp-ed895.firebaseapp.com',
    storageBucket: 'restaurantapp-ed895.appspot.com',
    measurementId: 'G-Y14L62S9EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxmj4JpHE3HAnax7j61KY_IV67aR6lg0M',
    appId: '1:345387617265:android:f7c67fa77aad032ddb1250',
    messagingSenderId: '345387617265',
    projectId: 'restaurantapp-ed895',
    storageBucket: 'restaurantapp-ed895.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg-6zT8ntuh9c6qNl9lSKN8RigdUsqynA',
    appId: '1:345387617265:ios:082672b0be91cd28db1250',
    messagingSenderId: '345387617265',
    projectId: 'restaurantapp-ed895',
    storageBucket: 'restaurantapp-ed895.appspot.com',
    iosBundleId: 'dev.leurs.restaurant.restaurantApp',
  );
}
